name: Update vault content

on:
  schedule:
    - cron: "0 11 * * WED" # Only on Wednesdays!
  workflow_dispatch:

env:
  QUARTZ_REPO: "quartz"
  VAULT_REPO: "notes"
  PUBLIC_ATTACHMENTS_FOLDER: "assets"
  YOUR_NOTES_FOLDER: "notes"

jobs:
  update_vault_content:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ngvt1n/es-research-notes-raw
        uses: actions/checkout@v4.2.2
        with:
          repository: "ngvt1n/es-research-notes-raw"
          ref: trunk
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: "${{ env.VAULT_REPO }}"

      - name: Clone this repo
        uses: actions/checkout@v4.2.2
        with:
          ref: tinv4
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: "${{ env.QUARTZ_REPO }}"

      - name: Delete everything in content/ except index.md
        run: |
          cd "${{ env.QUARTZ_REPO }}"
          mv content/index.md .
          rm -rf content
          mkdir content
          mv index.md content

      - name: Copy over media and files
        run: |
          cd "${{ env.VAULT_REPO }}"
          echo "----- Copying over public-only attachments"
          cp -vr "${{ env.PUBLIC_ATTACHMENTS_FOLDER }}" ../"${{ env.QUARTZ_REPO }}"/content
          echo -e "\n----- Copying over Markdown files"
          cp -vr "${{ env.YOUR_NOTES_FOLDER }}"/. ../"${{ env.QUARTZ_REPO }}"/content
          cd ../"${{ env.QUARTZ_REPO }}"/content
          mv "${{ env.PUBLIC_ATTACHMENTS_FOLDER }}" _files
        # ^ Include this last line if you want to rename your public folder

      - name: Print out current state of filesystem
        run: |
          echo "----- Folder: ${{ env.QUARTZ_REPO }}/"
          cd "${{ env.QUARTZ_REPO }}"
          ls | cat
          echo -e "\n----- Folder: ${{ env.QUARTZ_REPO }}/content/"
          ls content | cat
          echo -e "\n----- Folder: ${{ env.QUARTZ_REPO }}/content/_files"
          ls content/_files | cat
        # ^ NOTE: this uses the renamed folder name from above

      - name: Install Bun just to run literally two commands
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd "${{ env.QUARTZ_REPO }}"
          bun i

      - name: Setup Git config (user and email), necessary for commits
        run: |
          git config --global user.name "Tin Nguyen (quartz repo)"
          git config --global user.email "ngvt1n@github.com"

      - name: Sync Quartz repo
        run: |
          cd "${{ env.QUARTZ_REPO }}"
          bun quartz sync
